### ISSUE TITLE
Update User not firing up update method

### ISSUE THREAD

**Issue by arediey** [evercode1/sample-project#4]
I've been comparing both for updating user & profile. While updating profiles works perfectly, updating user is not. I tried to die and dump inside the update function on UserController.php but it did not trigger the function. However if i change the parameter to 

> // public function update(UserRequest $request, $id)
    public function update($id)

only then it will call the method. Here's route list comparing between user & profile controller.

> | PUT|PATCH | profile/{profile}                      | profile.update          | App\Http\Controllers\ProfileController@update 

>  | PUT|PATCH | user/{user}                            | user.update             | App\Http\Controllers\UserController@update

**Comment by evercode1** [comment]
You must be getting some kind of error message that you did not provide.  Do you have a UserRequest class?  Do you have the updateUser method on the User model?  Have you included the use statements where appropriate?  Those are common mistakes.  I'll close this for now, comment if you need further help.
