### ISSUE TITLE
Who can help me run the project?

### ISSUE THREAD

**Issue by s7evenseven** [evercode1/sample-project#5]
I'm fresher.
I install this project on cloud9, but it miss vendor folder, then i copy folder vendor from original lavarel code 5.4 on laravel.com. It still has error.
Who Can tell me step to install this project?

Thanks you.

**Comment by evercode1** [comment]
This is likely to cause errors, since the project installs several packages, which you will not get by simply copying from Laravel.com.  This sample-project repo is the project from the book, Laravel 5.4 For Beginners, so you can find complete instructions on how to build it there.
